Applied the bosco_cluster customizations to a newer base version and replaced the old one (including fixing an apparent bug).

diff --git a/bosco/bosco_cluster b/bosco/bosco_cluster
--- a/bosco/bosco_cluster
+++ b/bosco/bosco_cluster
@@ -1,12 +1,12 @@
 #!/bin/bash
-#Customized version of bosco cluster
+# cloud-copasi customized version of bosco_cluster
 # bosco_add_host: Used to install ssh keys and blahp on remote hosts.
 #
 # BOSCO can manage max 254 clusters, the # of clusters is returned sometime
 # as function exit code (by return) and this is modulo 256
 # see cluster_list_iterator, list
 
-#CopasiSE binary location
+# CopasiSE binary location
 copasise=$HOME/copasi/bin/CopasiSE
 
 # Bosco key location
@@ -17,6 +17,18 @@ PASSPHRASE_LOCATION=$HOME/.bosco/.pass
 
 # Bosco cluster list location
 CLUSTERLIST_LOCATION=$HOME/.bosco/.clusterlist
+
+# Check if invoked by a regular user on a BOSCO Multi User installation
+# if PRIVATE_ON_MU is defined will be unable to use glideins and to set the system rouitng
+condor_id=`condor_config_val condor_ids 2>/dev/null`
+if [ "x$condor_id" == "x" ]; then
+    condor_id=`id -u condor 2> /dev/null`
+else
+    condor_id=${condor_id%.*}
+fi 
+if [ ! "x$condor_id" == "x`id -u`" ]; then
+    PRIVATE_ON_MU=yes
+fi
 
 # SSH Control Path
 ssh_control_path="/tmp/bosco_ssh_control.%r@%h:%p"
@@ -40,8 +52,7 @@ commands:
  -a|--add host sched        Install and add a cluster, with scheduler sched
  -r|--remove [host]         Remove the installed cluster (first in list)
  -s|--status [host]         Get status of installed cluster
- -z|--pool_status [host]      Get status of cluster resources
-
+ -z|--pool_status [host]    Get status of cluster resources
  -t|--test [host]           Test the installed cluster (all clusters)
  -h|--help                  Show this help message
 
@@ -124,6 +135,9 @@ list()
 set_bosco_routing () {
     # $1 file to write the routing info into
     #  default to  LOCAL_CONFIG_DIR`/condor_config.bosco_routing
+    if [ -n "$PRIVATE_ON_MU" ]; then
+        return
+    fi
     if [ "x$1" != "x" ]; then
         dest_file=$1
     else
@@ -135,8 +149,9 @@ set_bosco_routing () {
         rm $dest_file 2>/dev/null
     else
         cat > $dest_file << EOF 
-grid_resource = $grid_res
-SUBMIT_EXPRS = grid_resource
+# Specifying a default grid_resource doesn't work in HTCondor 8.4.7+/8.5.5+
+#grid_resource = $grid_res
+#SUBMIT_EXPRS = grid_resource
 EOF
     fi
 }
@@ -247,15 +262,23 @@ ssh_find_remote () {
         echo "`$findplatform_path --url --force MAC`"
         return 0
     fi
-    cmd_out=`ssh $remote_host "python -c \"import platform; mydist = platform.dist(); print '%s%s' % (mydist[0], mydist[1][0])\"" 2>/dev/null`
+    cmd_out=`ssh $remote_host "python -c \"import platform; mydist = platform.dist(); print '%s%s' % (mydist[0], mydist[1])\"" 2>/dev/null`
     if [ $? -eq 0 ]; then
         # check for linux
         case "$cmd_out" in 
-            redhat5) echo "`$findplatform_path --url --force RH5`"
+            redhat5*) echo "`$findplatform_path --url --force RH5`"
                        ;;
-            redhat6) echo "`$findplatform_path --url --force RH6`"
+            redhat6*) echo "`$findplatform_path --url --force RH6`"
                        ;;
-            debian6) echo "`$findplatform_path --url --force DEB6`"
+            redhat7*) echo "`$findplatform_path --url --force RH7`"
+                       ;;
+            centos7*) echo "`$findplatform_path --url --force RH7`"
+                       ;;
+            debian6*) echo "`$findplatform_path --url --force DEB6`"
+                       ;;
+            debian7*) echo "`$findplatform_path --url --force DEB7`"
+                       ;;
+            Ubuntu12*) echo "`$findplatform_path --url --force UBUNTU12`"
                        ;;
             *) ;; 
         esac
@@ -337,8 +360,8 @@ add_cluster_to_list () {
     check_cluster_list2 $remote_host
     if [ $? -eq 0 ]; then
         tmpfile=`mktemp -t tmpclusterlist.XXXXXX`
-        sed "/entry=$remote_host max_queued=.*/d" $CLUSTERLIST_LOCATION > tmpfile
-        mv tmpfile $CLUSTERLIST_LOCATION
+        sed "/entry=$remote_host max_queued=.*/d" $CLUSTERLIST_LOCATION > $tmpfile
+        mv $tmpfile $CLUSTERLIST_LOCATION
     fi
 
     echo "entry=$remote_host max_queued=$max_queued cluster_type=$cluster_type" >> $CLUSTERLIST_LOCATION
@@ -617,28 +640,30 @@ End_of_Submit
     # NOTE: We will probably never see the job in running status, as it will
     #   finish immediately and Condor only polls its status periodically.
     # Check for job to run
-    #echo -n "Waiting for job to run... this could take a while (waiting 60 seconds)..."
-    #check_condor_q_classad "(ClusterId == $condor_jobid) && (JobStatus == 2)" 60
-    #if [ $? -eq 0 ]; then
-    #    echo "Failed"
-    #    echo "The job did not start in the 60 seconds we waited."
-    #    echo "This doesn't always mean there is something wrong, maybe the remote queue is long..."
-    #    echo "Here is the current status of the job:"
-    #    condor_q $condor_jobid
-    #    echo "You can look at job's log file at $log_file"
-    #    echo "for the job's current status"
-    #    exit 1
-    #else
-    #    echo "Passed!"
-    #fi
-    
-    echo -n "Waiting for job to exit... this could take a while (waiting 250 seconds)..."
-    check_condor_q_classad "(ClusterId == $condor_jobid) && (GridJobStatus==\"COMPLETED\") " 250
+    echo -n "Waiting for job to run... this could take a while (waiting 250 seconds)..."
+    check_condor_q_classad "(ClusterId == $condor_jobid) && (JobStatus == 2)" 250
     if [ $? -eq 0 ]; then
         echo "Failed"
-        echo "The job did not end in 250 seconds.  This is not always a bad thing..."
-        echo "Maybe condor is waiting longer to poll for job completion?"
+        echo "The job did not start in the 250 seconds we waited."
+        echo "This doesn't always mean there is something wrong, maybe the remote queue is long..."
         echo "Here is the current status of the job:"
+        condor_q $condor_jobid
+        echo "You can look at job's log file at $log_file"
+        echo "for the job's current status"
+        exit 1
+    else
+        echo "Passed!"
+    fi
+    
+    echo -n "Waiting for job to exit... this could take a while (waiting 60 seconds)..."
+    check_condor_q_classad "(ClusterId == $condor_jobid) && (GridJobStatus==\"COMPLETED\") " 60
+    if [ $? -eq 0 ]; then
+        cat << Error_message_end
+Failed
+The job did not end in 60 seconds.  This is not always a bad thing...
+Maybe condor is waiting longer to poll for job completion?
+Here is the current status of the job:"
+Error_message_end
         condor_q $condor_jobid
         # returning zero anyway, test considered successful 
         exit 0
@@ -678,13 +703,13 @@ End_of_Submit
     echo -n "Checking for job output..."
     output=`head -n 1 $test_stdout`
     expected_output=^COPASI\ [0-9]+\.[0-9]+\ .Build\ [0-9]+.$
-    if [[ "$output" =~ "$expected_output" ]] ; then
+    if [[ "$output" == "$expected_output" ]] ; then
 	echo "Passed!"
     else
 	echo "Failed"
 	echo "Job output should be:"
-	echo $output
-	echo "but isn't"
+        echo $expected_output
+        echo "but isn't"
 	echo "Showing contents of job stdout:"
 	cat $test_stdout
 	echo "Showing contents of job stderr:"
@@ -719,7 +744,6 @@ get_status () {
     done
     stop_ssh
 }
-
 
 get_pool_status () {
     remote_host=$1
@@ -774,7 +798,7 @@ while true; do
         -t|--test) test_cluster $2; exit 0 ;;
         -r|--remove) remove_cluster $2; exit 0;;
         -z|--pool_status) get_pool_status $2; exit 0;;
-
+        
         --) echo "No command found" >&2; usage; exit 1;;
         *) echo "Unknown option: $1" >&2; usage; exit 1;;
     esac
@@ -802,9 +826,9 @@ else
     if [ "$cluster_type" == "htcondor" ]; then
         cluster_type="condor"
     fi
-    if [ ! "$cluster_type" == "pbs" -a ! "$cluster_type" == "lsf" -a ! "$cluster_type" == "sge" -a ! "$cluster_type" == "condor" ]; then
+    if [ ! "$cluster_type" == "pbs" -a ! "$cluster_type" == "lsf" -a ! "$cluster_type" == "sge" -a ! "$cluster_type" == "condor" -a ! "$cluster_type" == "slurm" ]; then
         echo "Unrecognized batch system: $1 (normalized: $cluster_type)"
-        echo "Please specify one of the following: pbs, lsf, sge, condor"
+        echo "Please specify one of the following: pbs, lsf, sge, condor, slurm"
         exit 1
     fi
 fi
@@ -885,16 +909,17 @@ if [ "x$max_queued" == "x" ]; then
 fi
 
 
-# First, find the blahp
-glite_location=`condor_config_val GLITE_LOCATION`
-release_dir=`condor_config_val RELEASE_DIR`
-
-if [ "x$glite_location" == "x" -o "x$release_dir" == "x" ]; then
-    echo "Unable to determine condor locations using condor_config_val."
-    echo "There could be a problem in one of your condor config files."
-    echo "Exiting..."
-    exit 1
-fi
+# BOSCO is downloaded for the appropriate platform, not copied from the installation, this is not needed
+## First, find the blahp
+#glite_location=`condor_config_val GLITE_LOCATION`
+#release_dir=`condor_config_val RELEASE_DIR`
+#
+#if [ "x$glite_location" == "x" -o "x$release_dir" == "x" ]; then
+#    echo "Unable to determine condor locations using condor_config_val."
+#    echo "There could be a problem in one of your condor config files."
+#    echo "Exiting..."
+#    exit 1
+#fi
 
 
 # Find remote platform
@@ -920,7 +945,7 @@ if [ "x$url" == "x" ]; then
     # Attempt in a different way
     url=`ssh_find_remote $remote_host $findplatform_path`
     if [ "x$url" == "x" ]; then
-        echo "BOSCO is not supporting the remote platform."
+        echo "BOSCO does not support the remote host's OS."
         echo "Aborting installation to $remote_host."
         exit 1
     fi
@@ -980,11 +1005,14 @@ show_progress "Sending libraries to $remote_host" rsync -aq  $archive_dir/$libdi
 rsync -aq  $archive_dir/sbin/condor_ft-gahp $remote_glite_dir/bin 2>/dev/null
 
 # create the glidein
-export PYTHONPATH=`condor_config_val LIBEXEC`/campus_factory/python-lib
-export _campusfactory_GLIDEIN_DIRECTORY=`condor_config_val LIBEXEC`/campus_factory/share/glidein_jobs
-show_progress "Creating BOSCO for the WN's" glidein_creation $remote_host $archive_dir --outputtar=$tmp_dir/glideinExec.tar.gz
-rsync -aq  $tmp_dir/glideinExec.tar.gz $local_install_dir/campus_factory/ 2>/dev/null
-
+if [ -n "$PRIVATE_ON_MU" ]; then
+    echo "You are not running as the factory user. BOSCO Glideins disabled."
+else
+    export PYTHONPATH=`condor_config_val LIBEXEC`/campus_factory/python-lib
+    export _campusfactory_GLIDEIN_DIRECTORY=`condor_config_val LIBEXEC`/campus_factory/share/glidein_jobs
+    show_progress "Creating BOSCO for the WN's" glidein_creation $remote_host $archive_dir --outputtar=$tmp_dir/glideinExec.tar.gz
+    rsync -aq  $tmp_dir/glideinExec.tar.gz $local_install_dir/campus_factory/ 2>/dev/null
+fi
 
 cat >$remote_glite_dir/etc/condor_config.ft-gahp 2>/dev/null <<EOF
 BOSCO_SANDBOX_DIR=\$ENV(HOME)/$remote_sandbox_dir
@@ -992,22 +1020,36 @@ LOG=\$ENV(HOME)/$remote_base_dir_host/glite/log
 FT_GAHP_LOG=\$(LOG)/FTGahpLog
 SEC_CLIENT_AUTHENTICATION_METHODS = FS, PASSWORD
 SEC_PASSWORD_FILE = \$ENV(HOME)/$remote_base_dir_host/glite/etc/passwdfile
+USE_SHARED_PORT = False
+ENABLE_URL_TRANSFERS = False
 EOF
 
-# Generate the password file, if it doesn't already exist 
-bosco_passwd_file=`condor_config_val SEC_PASSWORD_FILE` 
-if [ "x$bosco_passwd_file" == "x" ]; then
-    echo "The BOSCO password file is not defined."
-    echo "Aborting installation to $remote_host."
-    rm -r $tmp_dir
-    exit 1
+# A regular user cannot write on system files
+# and will not need the password for grid universe jobs
+if [ ! -n "$PRIVATE_ON_MU" ]; then
+    # Generate the password file, if it doesn't already exist 
+    bosco_passwd_file=`condor_config_val SEC_PASSWORD_FILE` 
+    if [ "x$bosco_passwd_file" == "x" ]; then
+        echo "The BOSCO password file is not defined."
+        echo "Aborting installation to $remote_host."
+        rm -r $tmp_dir
+        exit 1
+    fi
+
+    if [ ! -e $bosco_passwd_file ]; then  
+        random_string=`echo $RANDOM | $MD5SUM | awk '{print $1}'` 
+        condor_store_cred -p $random_string -f $bosco_passwd_file 
+    fi
+
+    if [ ! -r  $bosco_passwd_file ]; then  
+        echo "Cannot read the BOSCO password file, check permissions of $bosco_passwd_file."
+        echo "Aborting installation to $remote_host."
+        rm -r $tmp_dir
+        exit 1
+    fi 
+    rsync -aq $bosco_passwd_file $local_install_dir/campus_factory/share/glidein_jobs 2>/dev/null
+    rsync -aq $bosco_passwd_file $remote_glite_dir/etc 2>/dev/null
 fi
-if [ ! -e $bosco_passwd_file ]; then  
-    random_string=`echo $RANDOM | $MD5SUM | awk '{print $1}'` 
-    condor_store_cred -p $random_string -f $bosco_passwd_file 
-fi
-rsync -aq $bosco_passwd_file $local_install_dir/campus_factory/share/glidein_jobs 2>/dev/null
-rsync -aq $bosco_passwd_file $remote_glite_dir/etc 2>/dev/null
 
 # Do the actual rsync
 show_progress "Installing on cluster $remote_host" rsync -aqK -e "ssh -o ControlMaster=auto -o ControlPath=$ssh_control_path" $local_install_dir $remote_host:
@@ -1035,14 +1077,17 @@ echo "Installation complete"
 
 
 # Configure condor
-min_queue_size=`get_min_queue`
-tmpfile=`mktemp -t tmpconfigfile.XXXXXX`
-condor_config_file=`condor_config_val LOCAL_CONFIG_FILE`
-sed "/GRIDMANAGER_MAX_SUBMITTED_JOBS_PER_RESOURCE.*/d" $condor_config_file > $tmpfile
-echo "GRIDMANAGER_MAX_SUBMITTED_JOBS_PER_RESOURCE=$min_queue_size" >> $tmpfile
-mv $tmpfile $condor_config_file
-chmod 644 $condor_config_file
-condor_reconfig 2>/dev/null 1>&2
+# Not if private user on BOSCO MU
+if [ ! -n "$PRIVATE_ON_MU" ]; then
+    min_queue_size=`get_min_queue`
+    tmpfile=`mktemp -t tmpconfigfile.XXXXXX`
+    condor_config_file=`condor_config_val LOCAL_CONFIG_FILE`
+    sed "/GRIDMANAGER_MAX_SUBMITTED_JOBS_PER_RESOURCE.*/d" $condor_config_file > $tmpfile
+    echo "GRIDMANAGER_MAX_SUBMITTED_JOBS_PER_RESOURCE=$min_queue_size" >> $tmpfile
+    mv $tmpfile $condor_config_file
+    chmod 644 $condor_config_file
+    condor_reconfig 2>/dev/null 1>&2
+fi
 
 # Submission instructions
 cat << EOM
